name: Build and release binary
on:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Resolve dependencies
        run:
          cargo update
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: |
          cargo build --release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/*.exe
